# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mng_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
