# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mng_app', '0002_auto_20160326_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 18, 26, 25, 833076, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 18, 26, 25, 833128, tzinfo=utc)),
        ),
    ]
