# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 23:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mng_app', '0008_auto_20160326_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 23, 40, 33, 803664, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 23, 40, 33, 803723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='security',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_mng_app.Portfolio'),
        ),
    ]
