# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 01:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mng_app', '0009_auto_20160326_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('-last_update_date',)},
        ),
        migrations.AlterModelOptions(
            name='security',
            options={'ordering': ('yid',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 27, 1, 2, 15, 196131, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 27, 1, 2, 15, 196188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='security',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_mng_app.Portfolio'),
        ),
    ]
