# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mng_app', '0010_auto_20160327_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 27, 9, 24, 50, 142807, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 27, 9, 24, 50, 142850, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='security',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='security',
            name='portfolio',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio_mng_app.Portfolio'),
        ),
    ]
