# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mng_app', '0014_auto_20160327_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yid', models.CharField(max_length=10)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='security',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 27, 13, 4, 8, 351056, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 27, 13, 4, 8, 351100, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='asset',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_mng_app.Portfolio'),
        ),
    ]
